#!/usr/bin/env bash

# Backup the original hosts file
cp /etc/hosts /etc/hosts.backup

# Modify the hosts file
sed -i 's/localhost$/localhost\n127.0.0.2/' /etc/hosts
sed -i 's/facebook.com$/facebook.com\n8.8.8.8/' /etc/hosts
